version: 1
formatters:
  simple:
    format: '%(levelname)-8s %(asctime)s: [%(name)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: 'paimon.log'
loggers:
  __main__:
    level: DEBUG
  'paimon':
    level: DEBUG
root:
  level: INFO
  handlers: [console, logfile]
disable_existing_loggers: False